# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c2cb030abb4423d6cbfb7dcf04fd371f0a1baefd72fff3a4b08405e51dae182100628e8fe92ece625faf586e619df1c704dfe53247c024f7cb0310af81d78a2

test:
  secret_key_base: 53910b2161b678ab2fa5b4c0309e26cb2dbebce44ca8cc49a9408acde562dc30e9a817b66d3d67d44234e6d04f8552601fb0c650045ebef32adc3e25565abc48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
